### ISSUE TITLE
Runtime error with spring-cloud-cloudfoundry-connector >v1.1.1

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry-community/spring-cloud-s3-service-connector#5]
```
git clone git@github.com:cloudfoundry-community/spring-cloud-s3-service-connector.git
mvn test # works
sed -i '' 's/1.0.0/1.1.1/' pom.xml
mvn test # runtime error
java.lang.NoSuchMethodError: org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator.<init>(Lorg/springframework/cloud/cloudfoundry/Tags;)V
        at org.cloudfoundry.community.service.storage.S3ServiceInfoCreator.<init>(S3ServiceInfoCreator.java:31)
```

but if you:
```
rm -rf target
mvn test
```

it will work.
Even though the src code remains compatible I assume there is a slight modification to the .class format that makes the byte code incompatible at runtime.
Would it be possible to upload a new version to maven that has been compiled with the latest version of [sring-cloud-cloudfoundry-connector](https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-cloudfoundry-connector) (v1.2.1)?

How is this jar released to maven and who has the right access?

**Comment by bodymindarts** [comment]
@davidehringer can you help with this?

**Comment by bodymindarts** [comment]
PR created pull/6

**Comment by ArthurHlt** [comment]
@bodymindarts you might be interested by this repo: https://github.com/Orange-OpenSource/spring-cloud-s3-connectors

**Comment by davidehringer** [comment]
@bodymindarts sorry, I was away for a few days.

This component is published to Maven Central via https://gaptap.atlassian.net/builds/browse/CFC-SPRIN

I created a `1.1.0` release including your dependency update in #6 .  It should show up in Maven Central soon depending on how long it takes their staging repos to sync to central.
